#для полной работы программы вам нужно скачать и разместить все mp3 файлы в нужную директорию.
import pygame
import sys
pygame.init()
pygame.mixer.init()
while True:
    bukva = str(input())
    if bukva == "a" or bukva == "A":
        print('███████████████')
        print('██╔═════════╗██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██╚═══╝▓╚═══╝██')
        print('███████████████')

        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "b" or bukva == "B":
        print('███████████████')
        print('██╔════════╗███')
        print('██║▓▓▓╔╗▓▓▓║███')
        print('██║▓▓▓╚╝▓▓▓╚╗██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██╚═════════╝██')
        print('███████████████')

    if bukva == "c" or bukva == "C":
        print('███████████████')
        print('██╔════════╗███')
        print('██║▓▓▓╔═╗▓▓║███')
        print('██║▓▓▓║█╚══╝███')
        print('██║▓▓▓║█╔══╗███')
        print('██║▓▓▓╚═╝▓▓║███')
        print('██╚════════╝███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "d" or bukva == "D":
        print('███████████████')
        print('██╔═════════╗██')
        print("██╚╗▓▓▓╔╗▓▓▓║██")
        print('███║▓▓▓║║▓▓▓║██')
        print('███║▓▓▓║║▓▓▓║██')
        print('██╔╝▓▓▓╚╝▓▓▓║██')
        print('██╚═════════╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "e" or bukva == "E":
        print("███████████████")
        print('████╔══════╗███')
        print('████║▓▓▓╔══╝███')
        print('████║▓▓▓╚══╗███')
        print('████║▓▓▓╔══╝███')
        print('████║▓▓▓╚══╗███')
        print('████╚══════╝███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "f" or bukva == "F":
        print('███████████████')
        print('███╔══════╗████')
        print('███║▓▓▓╔══╝████')
        print("███║▓▓▓╚══╗████")
        print('███║▓▓▓╔══╝████')
        print("███║▓▓▓║███████")
        print('███╚═══╝███████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "g" or bukva == "G":
        print('███████████████')
        print('██╔═════════╗██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓║█╚═══╝██')
        print('██║▓▓▓║╔═══╗███')
        print('██║▓▓▓╚╩═▓▓║███')
        print('██╚════════╝███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "h" or bukva == "H":
        print('███████████████')
        print('██╔═══╗█╔═══╗██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██╚═══╝█╚═══╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "i" or bukva == "I":
        print('███████████████')
        print('█████╔════╗████')
        print('█████╚╣▓▓╠╝████')
        print('██████║▓▓║█████')
        print('██████║▓▓║█████')
        print('█████╔╣▓▓╠╗████')
        print('█████╚════╝████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "j" or bukva == "J":
        print('███████████████')
        print('███████╔═══╗███')
        print('███████║▓▓▓║███')
        print('███████║▓▓▓║███')
        print('██╔═══╗║▓▓▓║███')
        print('██║▓▓▓╚╝▓▓▓║███')
        print('██╚════════╝███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "k" or bukva == "K":
        print('███████████████')
        print('███╔═══╗╔═══╗██')
        print('███║▓▓▓║║▓▓╔╝██')
        print('███║▓▓▓╚╝▓▓╝███')
        print('███║▓▓▓╔╗▓▓║███')
        print('███║▓▓▓║║▓▓╚╗██')
        print('███╚═══╝╚═══╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "l" or bukva == "L":
        print('███████████████')
        print('███╔═══╗███████')
        print('███║▓▓▓║███████')
        print('███║▓▓▓║███████')
        print('███║▓▓▓║█╔══╗██')
        print('███║▓▓▓╚═╝▓▓║██')
        print('███╚════════╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "m" or bukva == "M":
        print('███████████████')
        print('██╓───╖█╓───╖██')
        print('██║▓▓▓╙─╜▓▓▓║██')
        print('██║▓╓─╖▓╓─╖▓║██')
        print('██║▓║█║▓║█║▓║██')
        print('██║▓║█║▓║█║▓║██')
        print('██╙─╜█╙─╜█╙─╜██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "n" or bukva == "N":
        print('███████████████')
        print('███╓──╖███╓─╖██')
        print('███║▓▓╙─╖█║▓║██')
        print('███║▓╓─╖╙─╜▓║██')
        print('███║▓║█╙─╖▓▓║██')
        print('███║▓║███║▓▓║██')
        print('███╙─╜███╙──╜██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "o" or bukva == "O":
        print('███████████████')
        print('██╔═════════╗██')
        print('██║   ╔═╗   ║██')
        print('██║   ║ ║   ║██')
        print('██║   ║ ║   ║██')
        print('██║   ╚═╝   ║██')
        print('██╚═════════╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "p" or bukva == "P":
        print('███████████████')
        print('█╔═════════╗███')
        print('█║▓▓▓╔═╗▓▓▓║███')
        print('█║▓▓▓╚═╝▓▓▓║███')
        print('█║▓▓╔══════╝███')
        print('█║▓▓║██████████')
        print('█╚══╝██████████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)
    if bukva == "q" or bukva == "Q":
        print('███████████████')
        print('██╔═════════╗██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██╚═════──═╗║██')
        print('███████████╚╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "r" or bukva == "R":
        print('███████████████')
        print('██╔═════════╗██')
        print('██║▓▓▓╔═╗▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██║▓▓▓╔╗▓▓╔═╝██')
        print('██║▓▓▓║║▓▓╚═╗██')
        print('██╚═══╝╚════╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "s" or bukva == "S":
        print('███████████████')
        print('███╓───────╖███')
        print('███║▓▓╓────╜███')
        print('███║▓▓╙────╖███')
        print('███╙───╖▓▓▓║███')
        print('███╓───╜▓▓▓║███')
        print('███╙───────╜███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "t" or bukva == "T":
        print('███████████████')
        print('██╔════════╗███')
        print('██║▓╔╗▓▓╔╗▓║███')
        print('██╚═╝║▓▓║╚═╝███')
        print('█████║▓▓║██████')
        print('█████║▓▓║██████')
        print('█████╚══╝██████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "u" or bukva == "U":
        print('███████████████')
        print('██╔═══╗█╔═══╗██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓║█║▓▓▓║██')
        print('██║▓▓▓╚═╝▓▓▓║██')
        print('██╚═════════╝██')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "v" or bukva == "V":
        print('███████████████')
        print('██╓─╖████╓─╖███')
        print('██║▓╙╖██╓╜▓║███')
        print('██║▓▓║██║▓▓║███')
        print('██╙─╖╙──╜╓─╜███')
        print('████╙╖▓▓╓╜█████')
        print('█████╙──╜██████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "w" or bukva == "W":
        print('███████████████')
        print('███╔═╗╔═╗╔═╗███')
        print('███║▓║║▓║║▓║███')
        print('███║▓║║▓║║▓║███')
        print('███║▓╚╝▓╚╝▓║███')
        print('███╚═╗╔═╗╔═╝███')
        print('█████╚╝█╚╝█████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "x" or bukva == "X":
        print('███████████████')
        print('██╔═══╗╔═══╗███')
        print('██╚╗▓▓╚╝▓▓╔╝███')
        print('███╚╗▓▓▓▓╔╝████')
        print('███╔╝▓▓▓▓╚╗████')
        print('██╔╝▓▓╔╗▓▓╚╗███')
        print('██╚═══╝╚═══╝███')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "y" or bukva == "Y":
        print('███████████████')
        print('██╔═══╗██╔═══╗█')
        print('██║▓▓▓╚╗╔╝▓▓▓║█')
        print('██╚══╗▓╚╝▓╔══╝█')
        print('█████╚╗▓▓╔╝████')
        print('██████║▓▓║█████')
        print('██████╚══╝█████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    if bukva == "z" or bukva == "Z":
        print('███████████████')
        print('████╔═════╗████')
        print('████╚══╗▓▓║████')
        print('██████╔╝╔═╝████')
        print('█████╔╝╔╝██████')
        print('████╔╝▓╚══╗████')
        print('████╚═════╝████')
        print('███████████████')
        pygame.mixer.music.load(bukva + ".mp3")
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            pygame.time.Clock().tick(10)
    else:
        print("На этом мои полномочия все.")
        sys.exit()

    print("Хотите продолжить(yes - y or no - n) ?")
    a = str(input())
    while a != "y" and a != "n":
        print("вы инвалид , так вы хотите продолжить ? ")
    if a == "n":
        print('Не очень то и хотелось.')
        sys.exit()
    if a == "y":
        print("Спасибо, что пользуетесь нашими услугами!")
        continue
